#! /bin/sh

sxhkd &

bspc monitor -d term web code music irssi VI 

bspc config border_width         2
bspc config window_gap          18

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color Config
#bspc config presel_feedback_color \#828282
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Window Rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Vivaldi-stable desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

compton &
#wal -R -l &
polybar top &
polybar bottom &
wal -i ~/Pictures -l -g
